import type { Plant } from "./types"

export const featuredPlants: Plant[] = [
  {
    id: "1",
    name: "Monstera Deliciosa",
    scientificName: "Monstera deliciosa",
    slug: "monstera-deliciosa",
    description:
      "The Swiss Cheese Plant is famous for its quirky natural leaf holes and is a popular houseplant that can grow to impressive sizes.",
    category: "Indoor",
    difficulty: "Easy",
    sunlight: "Medium",
    water: "Weekly",
    temperature: "65-85°F",
    growthTime: "2-3 years to mature",
    soilType: "Well-draining potting mix",
    propagation: ["Stem cuttings", "Air layering"],
    commonProblems: ["Yellow leaves", "Brown spots", "Lack of fenestration"],
    tips: ["Allow soil to dry between waterings", "Provide support for climbing", "Wipe leaves to remove dust"],
  },
  {
    id: "2",
    name: "Snake Plant",
    scientificName: "Sansevieria trifasciata",
    slug: "snake-plant",
    description:
      "One of the most tolerant houseplants, the Snake Plant purifies air and thrives on neglect, making it perfect for beginners.",
    category: "Indoor",
    difficulty: "Easy",
    sunlight: "Low to High",
    water: "Monthly",
    temperature: "60-85°F",
    growthTime: "6-8 weeks for new growth",
    soilType: "Cactus or succulent mix",
    propagation: ["Division", "Leaf cuttings"],
    commonProblems: ["Root rot", "Mealybugs", "Brown tips"],
    tips: [
      "Allow soil to completely dry between waterings",
      "Can tolerate low light but grows faster in bright indirect light",
      "Rarely needs repotting",
    ],
  },
  {
    id: "3",
    name: "Fiddle Leaf Fig",
    scientificName: "Ficus lyrata",
    slug: "fiddle-leaf-fig",
    description:
      "With its distinctive violin-shaped leaves, the Fiddle Leaf Fig makes a dramatic statement in any space but requires consistent care.",
    category: "Indoor",
    difficulty: "Medium",
    sunlight: "Bright",
    water: "Weekly",
    temperature: "65-75°F",
    growthTime: "3-5 years to mature",
    soilType: "Well-draining potting mix",
    propagation: ["Stem cuttings", "Air layering"],
    commonProblems: ["Leaf drop", "Brown spots", "Root rot"],
    tips: [
      "Keep in a consistent spot with bright, indirect light",
      "Rotate occasionally for even growth",
      "Sensitive to drafts and temperature changes",
    ],
  },
  {
    id: "4",
    name: "Pothos",
    scientificName: "Epipremnum aureum",
    slug: "pothos",
    description:
      "A trailing vine with heart-shaped leaves, Pothos is incredibly versatile and one of the easiest houseplants to grow and propagate.",
    category: "Indoor",
    difficulty: "Easy",
    sunlight: "Low to Medium",
    water: "Weekly",
    temperature: "60-80°F",
    growthTime: "Rapid growth",
    soilType: "Standard potting mix",
    propagation: ["Stem cuttings in water or soil"],
    commonProblems: ["Yellow leaves", "Leggy growth", "Mealybugs"],
    tips: [
      "Tolerates low light but variegated varieties need more light",
      "Let soil dry slightly between waterings",
      "Trim regularly to encourage bushier growth",
    ],
  },
  {
    id: "5",
    name: "Basil",
    scientificName: "Ocimum basilicum",
    slug: "basil",
    description:
      "A fragrant culinary herb that's easy to grow indoors or outdoors, providing fresh leaves for cooking throughout the growing season.",
    category: "Herb",
    difficulty: "Easy",
    sunlight: "High",
    water: "Frequent",
    temperature: "70-85°F",
    growthTime: "3-4 weeks from seed",
    soilType: "Rich, moist soil",
    propagation: ["Seeds", "Stem cuttings"],
    commonProblems: ["Yellowing leaves", "Flowering", "Aphids"],
    tips: [
      "Pinch off flower buds to extend leaf production",
      "Harvest from the top to encourage bushier growth",
      "Water at the base to avoid wet leaves",
    ],
  },
  {
    id: "6",
    name: "Aloe Vera",
    scientificName: "Aloe barbadensis miller",
    slug: "aloe-vera",
    description:
      "A succulent with healing properties, Aloe Vera is both decorative and practical with its thick, gel-filled leaves.",
    category: "Succulent",
    difficulty: "Easy",
    sunlight: "Medium to High",
    water: "Bi-weekly",
    temperature: "55-80°F",
    growthTime: "3-4 years to mature",
    soilType: "Cactus or succulent mix",
    propagation: ["Offsets (pups)"],
    commonProblems: ["Root rot", "Brown spots", "Leggy growth"],
    tips: [
      "Allow soil to completely dry between waterings",
      "Needs good drainage",
      "Remove pups to control size and propagate new plants",
    ],
  },
]
